--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Ifera/ScoreHud
branches:Money:
- master
projects:
  ScoreHud:SkyFactionsPe
    icon: meta/ScoreHud.PNG
    libs:
      - src: buchwasa/ScoreFactory/ScoreFactory
        version: ^3.0.0
      - src: JackMD/UpdateNotifier/UpdateNotifier
        version: ^2.0.0
      - src: Ifera/ConfigUpdater/ConfigUpdater
        version: ^1.1.0
    lint:
      phpstan: false
...
